{% set version = "0.5.1" %}
{% set name = "mobie_utils" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/mobie/mobie-utils-python/archive/{{ version }}.tar.gz
  sha256: 628f9a5bafff0522664fca8fc9175549b4985de8884b7cf3bf4031f0058f9490

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - mobie.add_image = mobie.image_data:main
    - mobie.add_registered_source = mobie.registration:main
    - mobie.add_segmentation = mobie.segmentation:main
    - mobie.add_traces = mobie.traces:main
    - mobie.add_open_organelle_dataset = mobie.open_organelle:main
    - mobie.migrate_dataset = mobie.migration.migrate_dataset:main
    - mobie.migrate_project = mobie.migration.migrate_project:main
    - mobie.validate_dataset = mobie.validation.dataset:main
    - mobie.validate_project = mobie.validation.project:main
    - mobie.add_remote_metadata = mobie.metadata.remote_metadata:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - cluster_tools >=0.4.4
    - jsonschema
    - pandas
    - requests
    - s3fs
    - threadpoolctl >=0.3.3

test:
  imports:
    - mobie
    - mobie.metadata
  commands:
    - mobie.add_image -h
    - mobie.add_registered_source -h
    - mobie.add_segmentation -h
    - mobie.add_traces -h
    - mobie.add_open_organelle_dataset -h
    - mobie.migrate_dataset -h
    - mobie.migrate_project -h
    - mobie.validate_dataset -h
    - mobie.validate_project -h
  # the unit-tests fail on conda forge, I think because most of the jobs are submitted via luigi,
  # which causes trouble. But the tests pass for all OS iin the CI:
  # https://github.com/mobie/mobie-utils-python/blob/master/.github/workflows/build_and_test.yaml
  # source_files:
  #   - test/**/*.py
  # commands:
  #   - python -m unittest discover -s test -v

about:
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Python tools for MoBIE.
  home: https://github.com/mobie/mobie-utils-python

extra:
  recipe-maintainers:
    - constantinpape
